version = 1

[merge]
blocking_labels = ["wip", "don't-merge"]
method = "squash"

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pull_request_author = true
include_pull_request_url = true
strip_html_comments = true
cut_body_before = "<!-- commit body -->"

[update]
autoupdate_label = "autoupdate"
