name: autoupdate
on:
  push: {}
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action-unstable:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GH_API_TOKEN }}"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          PR_READY_STATE: "ready_for_review"

      - run: echo 'Merge conflicts found!'
        if: ${{ steps.autoupdate.outputs.conflicted }}

      - run: echo 'No merge conflicts'
        if: ${{ !steps.autoupdate.outputs.conflicted }}


# git fetch origin

# # Resetar as alterações locais para desfazer conflitos
# git reset --hard origin/main

# # Forçar a atualização da branch local para a branch remota
# git push --force origin HEAD
