name: Seu Fluxo de Trabalho - Autoupdate

on:
  pull_request:
    types:
      - labeled
jobs:
  seu-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Executar quando a label 'autoupdate' é adicionada
      run: |
        # Verificar se a label desejada está presente
        if [[ $(gh pr view ${{ github.event.number }} --json labels -q .[].name) == *"autoupdate"* ]]; then
          echo "Label 'autoupdate' adicionada à PR"
          # Coloque aqui os comandos ou scripts que você deseja executar
        else
          echo "Label 'autoupdate' não está presente na PR"
        fi


        # curl --location --request POST \
        #   --url 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels' \
        #   --H 'Accept: application/vnd.github.v3+json' \
        #   --H 'Authorization: Bearer ${{ secrets.GH_API_TOKEN }}' \
        #   --H 'Content-Type: application/json' \
        #   --d '{ "labels": ["enhancement"] }'

        # curl --location --request POST 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels' \
        #   --header 'Accept: application/vnd.github.v3+json' \
        #   --header 'Authorization: Bearer ${{ secrets.GH_API_TOKEN }}' \
        #   --header 'Content-Type: application/json' \
        #   --data-raw '{
        #       "labels": ["enhancement"]
        #   }'

        # curl -X DELETE \
        #   --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/autoupdate \
        #   --header 'Accept: application/vnd.github.v3+json' \
        #   -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        #   --fail
